# -*- coding: utf-8 -*-
"""Digital Clock (in Python).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWmka9DxaQYqNSTQJi9vj0wsw6yVDy3I
"""

import time
from datetime import datetime

while True:
  now = datetime.now()
  current_time = now.strftime("%H:%M:%S")

  print("\033[1;36m" + f"Digital Clock: {current_time}" + "\033[0m", end="\\r", flush=True)
  time.sleep(1)